trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        displayName: "Build and Test"
        steps:
          - task: DotNetCoreCLI@2
            displayName: "dotnet build"
            inputs:
              command: "build"
              projects: "**/*.csproj"
          - task: DotNetCoreCLI@2
            displayName: "dotnet test"
            inputs:
              command: "test"
              projects: "**/*Tests/*.csproj"
  - stage: Deliver
    jobs:
      - job: ReleaseArtifact
        displayName: "Release Artifact"
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              publishWebProjects: True
              arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
              zipAfterPublish: True
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "$(Build.ArtifactStagingDirectory)"
              artifactName: "musicApi"
  - stage: DeployDev
    jobs:
      - job: DeployToDev
        displayName: "Deploy to Dev Environment"
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Artifact"
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "musicApi"
              downloadPath: "$(System.ArtifactsDirectory)"
          - script: "echo Deploying to Dev Environment"
  - stage: DeployQAT
    jobs:
      - job: DeployToQAT
        displayName: "Deploy to QAT Environment"
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Artifact"
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "musicApi"
              downloadPath: "$(System.ArtifactsDirectory)"

          - script: "echo Deploying to QAT Environment"

  - stage: DeployStaging
    jobs:
      - job: DeployToStaging
        displayName: "Deploy to Staging Environment"
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Artifact"
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "musicApi"
              downloadPath: "$(System.ArtifactsDirectory)"

          - script: "echo Deploying to Staging Environment"

  - stage: DeployProduction
    jobs:
      - job: DeployToProduction
        displayName: "Deploy to Production Environment"
        steps:
          - task: DownloadBuildArtifacts@0
            displayName: "Download Artifact"
            inputs:
              buildType: "current"
              downloadType: "single"
              artifactName: "musicApi"
              downloadPath: "$(System.ArtifactsDirectory)"

          - script: "echo Deploying to Production Environment"
